config/urls.py
from django.contrib import admin
from django.urls import path, include

from board import views
from pybo.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/'에 해당하는 path
    path('board/', include('board.urls')),
]

pybo/urls.py
"""
파일명 : urls.py
설 명 : pybo 모든 URL 과 view 함수의 매핑 담당
생성일 : 2023-01-25
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""
from django.urls import path
from . import views  # 현재 디렉토리의 views 모듈
from .views import base_views, question_views, answer_views, boot_views

app_name = 'pybo'
urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),  # views index 로 매핑
    path('<int:question_id>/', base_views.detail, name='detail'),

    # boot_views.py
    # temp menu
    path('boot/menu', boot_views.boot_menu, name='boot_menu'),
    # bootstrap template
    path('boot/list/', boot_views.boot_list, name='boot_list'),
    path('boot/reg/', boot_views.boot_reg, name='boot_reg'),
    # crawling
    path('crawling/cgv/', boot_views.crawling_cgv, name='crawling_cgv'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models


# 질문 Question 클래스 생성 : subject, content, create_date
class Question(models.Model):
    subject = models.CharField(max_length=200)  # 글자수 제한
    content = models.TextField()  # 글자수 제한이 없는 경우
    create_date = models.DateTimeField()  # 날짜 + 시간
    modify_date = models.DateTimeField(null=True, blank=True)

    # author 필드 추가 : 글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_question')  # 회원 테이블에 사용자 정보가 삭제되면 Question 테이블 질문도 모두 삭제

    #  추천인 추가
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    # 답변에 연관된 질문이 삭제되면 답변도 모두 삭제하세요.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()  # 글자수 제한이 없는 경우
    create_date = models.DateTimeField()  # 날짜 + 시간
    # 수정일시 추가
    modify_date = models.DateTimeField(null=True, blank=True)

    # author 필드 추가 : 글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')

    voter = models.ManyToManyField(User, related_name='voter_answer')

    # 입력필드에 null 허용하기
    # author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.content

pybo/forms.py
"""
파일명 : forms.py
설 명 : html form 관리
생성일 : 2023-02-01
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""

from django import forms
from pybo.models import Question, Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer  # 사용할 Answer model
        fields = ['content']
        widgets = {
            # class = "form-control"
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'content': '답변내용',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 Question model
        fields = ['subject', 'content']  # QuestionForm 사용할 question model 의 속성
        widgets = {
            # class = "form-control"
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from pybo.forms import QuestionForm, AnswerForm
from pybo.models import Question, Answer


# ctrl + alt + o : import 정리

# Create your views here.
@login_required(login_url='common:login')
def answer_create(request, question_id):
    """답변등록"""
    # logging.info('answer_create question_id:{}'.format(question_id))
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.create_date = timezone.now()
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()

    # form validation
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    # Question 과 Answer 처럼 서로 연결되어 있는 경우
    # 연결모델명_set 연결데이터를 조회할 수 있다.


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    # 1. answer id 에 해당되는 데이터 조회
    answer = get_object_or_404(Answer, pk=answer_id)

    # 2. 수정 권한 체크 : 권한이 없는 경우 메세지 전달
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    # 3. POST : 수정
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            # 수정 화면
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id),
                                                  answer.id))

    # 4. GET : 수정 form 전달
    else:
        form = QuestionForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 댓글은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id),
                                          answer.id))

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from pybo.models import Question


# Create your views here.
def detail(request, question_id):
    """question 상세"""
    # logging.info('1.question_id:{}'.format(question_id))
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    # logging.info('2.question:{}'.format(question))
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def index(request):
    """question list"""
    # list order create_date desc
    # logging.info('index 레벨로 출력')

    # 입력인자
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')
    div = request.GET.get('div', '')
    per_page = request.GET.get('per_page', '10')
    # logging.info('page:{}'.format(page))

    question_list = Question.objects.order_by('-create_date')  # order_by('-필드') desc,order_by('필드') asc
    if kw:
        if div == '10':
            question_list = question_list.filter(
                Q(subject__icontains=kw)  # 제목 검색
            ).distinct()
        elif div == '20':
            question_list = question_list.filter(
                Q(content__icontains=kw)  # 내용 검색
            ).distinct()
        elif div == '30':
            question_list = question_list.filter(
                Q(author__username__icontains=kw)  # 작성자 검색
            ).distinct()
        else:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()
    # paging
    paginator = Paginator(question_list, per_page)
    page_obj = paginator.get_page(page)
    # paginator.count : 전체 게시물 개수
    # paginator.per_page : 페이지 당 보여줄 게시물 개수
    # paginator.page_range : 페이지 범위
    # number : 현재 페이지 번호
    # has_next : 다음 페이지 유무
    # has_previous : 이전 페이지 유무
    # has_other_pages
    # next_page_number : 다음 페이지 번호
    # previous_page_number : 이전 페이지 번호
    # start_index : 현재 페이지 시작 번호
    # end_index : 현재 페이지 끝 번호
    # question_list = Question.objects.filter(id=99)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'div': div, 'per_page': per_page}
    # logging.info('question_list:{}'.format(question_list))
    return render(request, 'pybo/question_list.html', context)

pybo/views/boot_views.py
import requests
from bs4 import BeautifulSoup
from django.shortcuts import render


# Create your views here.
def boot_menu(request):
    """개발에 사용되는 임시메뉴"""
    return render(request, 'pybo/menu.html')


def boot_reg(request):
    return render(request, 'pybo/reg.html')


# bootstrap list
def boot_list(request):
    """bootstrap template"""
    return render(request, 'pybo/list.html')


def crawling_cgv(request):
    """http://www.cgv.co.kr/movies/?lt=1&ft=0"""
    url = 'http://www.cgv.co.kr/movies/?lt=1&ft=0'
    response = requests.get(url)
    context = {}
    if 200 == response.status_code:
        html = response.text
        # print('html:{}'.format(html))
        soup = BeautifulSoup(html, 'html.parser')
        title = soup.select('div.box-contents strong.title')
        percent = soup.select('strong.percent span')
        poster = soup.select('span.thumb-image img')
        title_list = []  # 제목
        percent_list = []  # 예매율
        poster_list = []  # 포스터
        print('title:{}'.format(title))
        for page in range(0, 7, 1):
            print('title[{}]:{}'.format(page, title[page].get_text()), end=", ")
            title_list.append(title[page].get_text())
            print('percent[{}]:{}'.format(page, percent[page].get_text()))
            percent_list.append(percent[page].get_text())
            print('poster[{}]:{}'.format(page, poster[page].get('src')))
            poster_list.append(poster[page].get('src'))
        context = {'context': zip(title_list, percent_list, poster_list)}
    else:
        print('접속 오류 response.status_code:{}'.format(response.status_code))
    return render(request, 'pybo/crawling_cgv.html', context)

pybo/views/question_views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from pybo.forms import QuestionForm
from pybo.models import Question


# Create your views here.
@login_required(login_url='common:login')
def question_create(request):
    """질문등록"""

    # logging.info('1.request.method:{}'.format(request.method))
    if request.method == 'POST':
        # logging.info('2.question_create post')
        # 저장
        form = QuestionForm(request.POST)  # request.POST 데이터(subject, content 자동 생성)
        # logging.info('3.question_create post')
        # form(질문등록)이 유효하면
        if form.is_valid():
            # logging.info('4.form.is_valid():{}'.format(form.is_valid()))
            question = form.save(commit=False)  # subject, content 만 저장(commit 은 하지 않음)
            question.create_date = timezone.now()
            question.author = request.user
            question.save()  # 날짜까지 생성해서 저장(Commit)
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            logging.info(question.id)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    """질문: 좋아요"""
    question = get_object_or_404(Question, pk=question_id)
    # 본인 글은 추천하지 못하게
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

templates/pybo/answer_form.html
{%extends 'base.html'%}
{%block content%}
<!--답변 수정-->
<div class="container my-3">
    <!--제목-->
    <div class="text-start mb-5">
        <h2 class="p-5">답변 수정</h2>
    </div>
    <!--제목 end-->
    <!--등록 form-->
    <form method="post">
        {%csrf_token%}
        <!--form validation 기능-->
        {%include 'form_errors.html'%}
        <!--form validation 기능 end-->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <div>
                <textarea name="content" id="content" cols="20" rows="10" class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
        </div>
        <!--모델 폼과 연결된 subject, content 의 값을 저장할 수 있는 form 생성-->
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
    <!--등록 form end-->
</div>
<!--container end-->
{%endblock%}

templates/pybo/menu.html
{%extends 'base.html'%}
{%block content%}
<!--container-->
<div class="container">
    <!--제목-->
    <div class="text-start mb-5">
        <h2 class="p-5">임시메뉴</h2>
    </div>
    <!--제목 end-->
    <!--검색, 버튼-->
    <div class="d-grid gap-2 d-md-flex justify-content-end">
        <!--검색 form-->
        <form action="#" class="col-sm-11 col-md-11 col-lg-11 text-end">
            <select class="form-select-sm">
                <option selected value="">전체</option>
                <option value="10">제목</option>
                <option value="20">내용</option>
                <option value="30">작성자</option>
            </select>
            <input type="text" class="form-control-sm" placeholder="검색어" name="" id="">
            <select class="form-select-sm">
                <option value="10">10</option>
                <option value="20">20</option>
                <option value="30">30</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
        </form>
        <!--검색 form end-->

        <!--button-->
        <div class="col-sm-1 col-md-1 col-lg-1 text-end">
            <input type="button" class="btn btn-primary btn-sm" value="조회">
            <button type="button" class="btn btn-primary btn-sm" onclick="location.href='{%url 'pybo:boot_reg'%}'">등록</button>
        </div>
        <!--button end-->
    </div>
    <!--검색, 버튼 end-->
</div>
<!--table-->
<div class="container table-responsive mt-5">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr class="table-dark">
            <th scope="col" class="text-center">No.</th>
            <th scope="col" class="text-center">제목</th>
            <th scope="col" class="text-center">설명</th>
            <th scope="col" class="text-center">작성일</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-center">1</td>
<!--            <td class="text-start"><a href="./list/">질문목록</a></td>-->
            <td class="text-start"><a href="{%url 'pybo:index'%}">질문목록</a></td>
            <td class="text-center">질문목록</td>
            <td class="text-center">2023-01-30</td>
        </tr>
        <tr>
            <td class="text-center">2</td>
            <td class="text-start"><a href="{%url 'pybo:boot_list'%}">boot 목록</a></td>
            <td class="text-center">bootstrap 목록 템플릿</td>
            <td class="text-center">2023-01-31</td>
        </tr>
        <tr>
            <td class="text-center">3</td>
            <td class="text-start"><a href="{%url 'pybo:boot_reg'%}">boot 등록</a></td>
            <td class="text-center">bootstrap 등록 템플릿</td>
            <td class="text-center">2023-01-31</td>
        </tr>
        </tbody>
    </table>
</div>
<!--table end-->

<!--paging-->
<div class="d-grid gap-2 d-md-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
<!--paging-end-->

<!--container end-->
{%endblock%}

templates/pybo/question_detail.html
{%extends 'base.html'%}
{%load pybo_filter%}
{%block content%}
<!--container-->
<div class="container">
    <!--message 표시-->
    {%if messages%}
    <div class="alert alert-danger my-3" role="alert">
        {%for message in messages%}
        <strong>{{message.tags}}</strong>
        <ul>
            <li>{{message.message}}</li>
        </ul>
        {%endfor%}
    </div>
    {%endif%}
    <!-- 질문 py: 상하 패딩!-->
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-text p-5 pb-5">{{question.content|mark}}</div>
        <div class="d-flex justify-content-end" style="opacity:50%">
            {%if question.modify_date%}
            <div class="badge bg-light text-dark p-2 text-start mx-3" style="border:2px solid grey">
                <div class="mb-3">modified by <strong
                        style="text-decoration:underline">{{question.author.username}}</strong></div>
                <div>{{question.modify_date}}</div>
            </div>
            {%else%}
            <div class="badge bg-light text-dark p-2 text-start mx-3" style="border:2px solid grey">
                <div class="mk-2 mb-3 text-decoration-underline">registered by
                    <strong style="text-decoration:underline">{{question.author.username}}</strong>
                </div>
                <div>{{question.create_date}}</div>
            </div>
            {%endif%}
        </div>
        <div class="my-3 p-3">
            <a class="recommend btn btn-sm btn-outline-secondary" data-uri="{%url 'pybo:question_vote' question.id%}"
               href="javascript:void(0)" {%if user in question.voter.all%} style="background-color:green;color:white" {%endif%}>추천<span
                    class="badge rounded-pill bg-success">{{question.voter.count}}</span></a>
            {%if request.user == question.author%}
            <a class="btn btn-sm btn-outline-secondary" href="{%url 'pybo:question_modify' question.id%}">수정</a>
            <a class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id  %}"
               href="javascript:void(0)">삭제</a>
            {%endif%}
        </div>
    </div>
    <button class="btn btn-sm" style="margin-top:10px;background-color:#506EA5;color:white;" type="button"
        onclick="location.href='/'">목록이동
    </button>
    <a href="{%url 'pybo:question_create'%}" class="btn btn-primary btn-sm" style="margin-top:10px;float:right">질문 등록</a>
    <!--질문 end-->
    <!--답변-->
    <h5 class="border-bottom py-2 my-3">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {%for answer in question.answer_set.all%}
    <a id="answer_{{answer.id}}"></a>
    <div class="card my-1">
        <div class="card-text p-5 pb-1">{{answer.content|mark}}</div>
        <div class="d-flex justify-content-end" style="opacity:50%">
            {%if answer.modify_date%}
            <div class="badge bg-light text-dark p-2 text-start mx-3" style="border:2px solid grey">
                <div class="mb-3">modified by <strong
                        style="text-decoration:underline">{{answer.author.username}}</strong></div>
                <div>{{answer.modify_date}}</div>
            </div>
            {%else%}
            <div class="badge bg-light text-dark p-2 text-start mx-3" style="border:2px solid grey">
                <div class="mk-2 mb-3">registered by <strong style="text-decoration:underline">{{answer.author.username}}</strong>
                </div>
                <div>{{answer.create_date}}</div>
            </div>
            {%endif%}
        </div>
        <div class="my-3 p-3">
            <a class="recommend btn btn-sm btn-outline-secondary" data-uri="{%url 'pybo:answer_vote' answer.id%}"
               href="javascript:void(0)">추천<span class="badge rounded-pill bg-success">{{answer.voter.count}}</span></a>
            {%if request.user == answer.author%}
            <a class="btn btn-sm btn-outline-secondary" href="{%url 'pybo:answer_modify' answer.id%}">수정</a>
            <a class="delete btn btn-sm btn-outline-secondary" data-uri="{%url 'pybo:answer_delete' answer.id%}"
               href="#">삭제</a>
            {%endif%}
        </div>
    </div>
    {%endfor%}
    <!--답변 end-->
    <!--답변 등록-->
    <form action="{%url 'pybo:answer_create' question.id %}" class="my-3" method="post" name="answer_form">
        {%csrf_token%}
        <!--form validation 기능-->
        {%include 'form_errors.html'%}
        <!--form validation 기능 end-->
        <div class="mb-3">
            <label class="col-form-label" for="content">답변 내용</label>
            <textarea
                    {%if not user.is_authenticated%}disabled{%endif%} class="form-control p-5" cols="20" id="content"
                    name="content" rows="3"
            ></textarea>
        </div>
        <!--        <input class="btn btn-primary btn-sm" type="button" value="답변등록" onclick="javascript:doSave();">-->
        <input class="btn btn-primary btn-sm" id="submit_btn" type="submit" value="답변등록">
    </form>
    <!--답변 등록 end-->
    <script>
        function doSave(){
            <!--console.log('doSave');-->
            let form = document.answer_form;
            let content = form.content.value;
            console.log('content'+content);
            if(isEmpty(content) == true){
                alert('내용을 입력하세요');
                form.content.focus();
                return;
            }
            //서버로 전송
            form.submit;
        };
    </script>
</div>
<!--container end-->
{%endblock%}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
<!--const delete_elements = document.querySelectorAll(".delete");-->
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName('recommend');
Array.from(recommend_elements).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm('정말로 추천하시겠습니까?')){
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pybo/question_detail_bak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%load static%} <!--css, js, images 로딩 최상단에 위치!-->
    <link rel="stylesheet" type="text/css" href="{%static 'style.css'%}">
    <!--Bootstrap-->
    <link rel="stylesheet" type="text/css" href="{%static 'bootstrap.min.css'%}">
    <title>Title</title>
</head>
<body>
<h1>{{question.subject}}</h1>
<div>{{question.content}}</div>
<!--등록된 답변 출력-->
<h5>{{question.answer_set.count}}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {%for answer in question.answer_set.all%}
        <li>{{answer.content}}</li>
        {%endfor%}
    </ul>
</div>
<form action="{%url 'pybo:answer_create' question.id %}" method="post">
    {%csrf_token%}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="답변등록">
</form>
</body>
</html>

templates/pybo/question_form.html
{%extends 'base.html'%}
{%block content%}
<!--container-->
<div class="container">
    <!--제목-->
    <div class="text-start mb-5">
        <h2 class="p-5">질문등록</h2>
    </div>
    <!--제목 end-->

    <!--등록 form-->
<!--    <form method="post" class="post-form my-3" action="{%url 'pybo:question_create'%}">-->
    <form method="post" class="post-form my-3">
        {%csrf_token%}
        <!--form validation 기능-->
        {%include 'form_errors.html'%}
        <!--form validation 기능 end-->
        <div class="mb-3">
            <!--템플릿 필터 : 변수 값을 특정한 포맷으로 변형하는 기능.-->
            <label for="subject" class="col-form-label">제목</label>
            <div class="">
                <input type="text" class="form-control" id="subject" name="subject"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
        </div>
        <div class="mb-3">
            <label for="content" class="col-form-label">내용</label>
            <div class="">
                <!--content 에 데이터가 없으면 None 이라는 문자열이 표시됨, None 대신 공백으로 표시하세요.-->
                <textarea name="content" id="content" cols="20" rows="10" class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
        </div>
        <!--모델 폼과 연결된 subject, content 의 값을 저장할 수 있는 form 생성-->
        <button type="submit" class="btn btn-primary btn-sm">등록</button>
    </form>
    <!--등록 form end-->
</div>
<!--container end-->
{%endblock%}