common/urls.py
"""
파일명 : urls.py
설 명 :
생성일 : 2023-02-06
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    # django.contrib.auth 앱의 LoginView 클래스를 활용
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),

    # logout: LogoutView
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    # signup: 회원가입
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from board import views
from pybo.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/'에 해당하는 path
    path('board/', include('board.urls')),
]

pybo/urls.py
"""
파일명 : urls.py
설 명 : pybo 모든 URL 과 view 함수의 매핑 담당
생성일 : 2023-01-25
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""
from django.urls import path
from . import views  # 현재 디렉토리의 views 모듈
from .views import base_views, question_views, answer_views, boot_views

app_name = 'pybo'
urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),  # views index 로 매핑
    path('<int:question_id>/', base_views.detail, name='detail'),

    # boot_views.py
    # temp menu
    path('boot/menu', boot_views.boot_menu, name='boot_menu'),
    # bootstrap template
    path('boot/list/', boot_views.boot_list, name='boot_list'),
    path('boot/reg/', boot_views.boot_reg, name='boot_reg'),
    # crawling
    path('crawling/cgv/', boot_views.crawling_cgv, name='crawling_cgv'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from pybo.models import Question


# Create your views here.
def detail(request, question_id):
    """question 상세"""
    # logging.info('1.question_id:{}'.format(question_id))
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    # logging.info('2.question:{}'.format(question))
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def index(request):
    """question list"""
    # list order create_date desc
    # logging.info('index 레벨로 출력')

    # 입력인자
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')
    div = request.GET.get('div', '')
    per_page = request.GET.get('per_page', '10')
    # logging.info('page:{}'.format(page))

    question_list = Question.objects.order_by('-create_date')  # order_by('-필드') desc,order_by('필드') asc
    if kw:
        if div == '10':
            question_list = question_list.filter(
                Q(subject__icontains=kw)  # 제목 검색
            ).distinct()
        elif div == '20':
            question_list = question_list.filter(
                Q(content__icontains=kw)  # 내용 검색
            ).distinct()
        elif div == '30':
            question_list = question_list.filter(
                Q(author__username__icontains=kw)  # 작성자 검색
            ).distinct()
        else:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()
    # paging
    paginator = Paginator(question_list, per_page)
    page_obj = paginator.get_page(page)
    # paginator.count : 전체 게시물 개수
    # paginator.per_page : 페이지 당 보여줄 게시물 개수
    # paginator.page_range : 페이지 범위
    # number : 현재 페이지 번호
    # has_next : 다음 페이지 유무
    # has_previous : 이전 페이지 유무
    # has_other_pages
    # next_page_number : 다음 페이지 번호
    # previous_page_number : 이전 페이지 번호
    # start_index : 현재 페이지 시작 번호
    # end_index : 현재 페이지 끝 번호
    # question_list = Question.objects.filter(id=99)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'div': div, 'per_page': per_page}
    # logging.info('question_list:{}'.format(question_list))
    return render(request, 'pybo/question_list.html', context)

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--favicon-->
    <link rel="shortcut icon" href="{%static 'favicon.ico'%}" type="image/x-icon">
    <!--favicon end-->
    <link rel="stylesheet" type="text/css" href="{%static 'style.css'%}">
    <!--Bootstrap-->
    <link rel="stylesheet" type="text/css" href="{%static 'bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script src="{%static 'common.js'%}"></script>
    <script src="{%static 'bootstrap.min.js'%}"></script>
    <title>Pybo</title>
</head>
<body>
<!--네비게이션바-->
{%include 'navbar.html'%}
<!--네비게이션바 end-->
<!--기본 템플릿 안에 삽입될 내용-->
{%block content%}
{%endblock%}
<!--기본 템플릿 안에 삽입될 내용 end-->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
<a href="./"
   style="display:scroll;position:fixed;bottom:50px;right:50px;color:white;background-color:black;padding:10px">top</a>
</body>
</html>

templates/form_errors.html
{%if form.errors%}
<div class="alert alert-danger" role="alert">
    {%for field in form%}
    {%if field.errors%}
    <div><strong>{{ field.label }}</strong></div>
    {{ field.errors }}
    {%endif%}
    {%endfor%}
</div>
{%endif%}

templates/navbar.html
<nav class="navbar navbar-expand-lg border-bottom navbar-dark bg-primary ps-2">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="justify-content-start">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'pybo:boot_list' %}" aria-current="page">템플릿_리스트</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'pybo:boot_reg' %}" aria-current="page">템플릿_등록</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'pybo:crawling_cgv' %}" aria-current="page">무비차트</a>
                    </li>
                </ul>
            </div>
            <div class="justify-content-end">
                <ul class="navbar-nav">
                    <!--로그인-->
                    <li class="nav-item justify-content-end">
                        <!--로그인 정보가 있는 경우-->
                        {%if user.is_authenticated%}<!--로그인 상태, is_anonymous: 로그아웃 상태-->
                            {{ user.username }}<a class="nav-link active d-inline " href="{% url 'common:logout' %}"
                                                  aria-current="page">(로그아웃<i class="bi bi-box-arrow-right"></i>)</a>
                        {% else %}
                            <a class="nav-link active" href="{% url 'common:login' %}" aria-current="page">로그인<i
                                    class="bi bi-box-arrow-in-right"></i></a>
                            </li>
                            <li class="nav-item justify-content-end">
                            <a class="nav-link active" href="{% url 'common:signup' %}" aria-current="page">회원 가입</a>
                        {% endif %}
                        </li>
                </ul>
            </div>
        </div>
    </div>
</nav>