board/urls.py
"""
파일명 : urls.py
설 명 : board urls
생성일 : 2023-02-15
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='board_create'),
    path('<int:board_id>/', views.detail, name='board_detail'),
    path('modify/<int:board_id>/', views.modify, name='board_modify'),
    path('delete/<int:board_id>/', views.delete, name='board_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from board import views
from pybo.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/'에 해당하는 path
    path('board/', include('board.urls')),
]

pybo/urls.py
"""
파일명 : urls.py
설 명 : pybo 모든 URL 과 view 함수의 매핑 담당
생성일 : 2023-01-25
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""
from django.urls import path
from . import views  # 현재 디렉토리의 views 모듈
from .views import base_views, question_views, answer_views, boot_views

app_name = 'pybo'
urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),  # views index 로 매핑
    path('<int:question_id>/', base_views.detail, name='detail'),

    # boot_views.py
    # temp menu
    path('boot/menu', boot_views.boot_menu, name='boot_menu'),
    # bootstrap template
    path('boot/list/', boot_views.boot_list, name='boot_list'),
    path('boot/reg/', boot_views.boot_reg, name='boot_reg'),
    # crawling
    path('crawling/cgv/', boot_views.crawling_cgv, name='crawling_cgv'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

board/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_board')

board/forms.py
"""
파일명 : forms.py
설 명 :
생성일 : 2023-02-15
생성자 : highprime
since 2023.01.09 Copyright (C) by KandJang All right reserved.
"""
from django import forms

from board.models import Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board  # 사용할 Board model
        fields = ['subject', 'content']  # BoardForm 사용할 board model 의 속성
        widgets = {
            # class = "form-control"
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

board/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.forms import BoardForm
from board.models import Board


# Create your views here.
def index(request):
    # 입력인자
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')
    div = request.GET.get('div', '')
    per_page = request.GET.get('per_page', '10')

    board_list = Board.objects.order_by('-create_date')  # order_by('-필드') desc,order_by('필드') asc
    if kw:
        if div == '10':
            board_list = board_list.filter(
                Q(subject__icontains=kw)  # 제목 검색
            ).distinct()
        elif div == '20':
            board_list = board_list.filter(
                Q(content__icontains=kw)  # 내용 검색
            ).distinct()
        elif div == '30':
            board_list = board_list.filter(
                Q(author__username__icontains=kw)  # 작성자 검색
            ).distinct()
        else:
            board_list = board_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(author__username__icontains=kw)  # 질문 글쓴이 검색
            ).distinct()
    # paging
    paginator = Paginator(board_list, per_page)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'page': page, 'kw': kw, 'div': div, 'per_page': per_page}
    return render(request, 'board/board_list.html', context)


def detail(request, board_id):
    """board 상세"""
    board = get_object_or_404(Board, pk=board_id)
    context = {'board': board}
    return render(request, 'board/board_detail.html', context)


@login_required(login_url='common:login')
def create(request):
    """게시판등록"""

    if request.method == 'POST':
        # 저장
        form = BoardForm(request.POST)  # request.POST 데이터(subject, content 자동 생성)
        # form(질문등록)이 유효하면
        if form.is_valid():
            board = form.save(commit=False)  # subject, content 만 저장(commit 은 하지 않음)
            board.create_date = timezone.now()
            board.author = request.user
            board.save()  # 날짜까지 생성해서 저장(Commit)
            return redirect('board:index')
    else:
        form = BoardForm()
    context = {'form': form}
    return render(request, 'board/board_form.html', context)


@login_required(login_url='common:login')
def modify(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:board_detail', board_id=board.id)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            logging.info(board.id)
            board.modify_date = timezone.now()
            board.save()
            return redirect('board:board_detail', board_id=board.id)
    else:
        form = BoardForm(instance=board)
    context = {'form': form}
    return render(request, 'board/board_form.html', context)


@login_required(login_url='common:login')
def delete(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('board:board_detail', board_id=board.id)
    board.delete()
    return redirect('board:index')

templates/board/board_detail.html
{%extends 'base.html'%}
{%load pybo_filter%}
{%block content%}
<!--container-->
<div class="container">
    <!--message 표시-->
    {%if messages%}
    <div class="alert alert-danger my-3" role="alert">
        {%for message in messages%}
        <strong>{{message.tags}}</strong>
        <ul>
            <li>{{message.message}}</li>
        </ul>
        {%endfor%}
    </div>
    {%endif%}
    <!-- 질문 py: 상하 패딩!-->
    <h2 class="border-bottom py-2">{{board.subject}}</h2>
    <div class="card my-3">
        <div class="card-text p-5 pb-5">{{board.content|mark}}</div>
        <div class="d-flex justify-content-end" style="opacity:50%">
            {%if board.modify_date%}
            <div class="badge bg-light text-dark p-2 text-start mx-3" style="border:2px solid grey">
                <div class="mb-3">modified by <strong
                        style="text-decoration:underline">{{board.author.username}}</strong></div>
                <div>{{board.modify_date}}</div>
            </div>
            {%else%}
            <div class="badge bg-light text-dark p-2 text-start mx-3" style="border:2px solid grey">
                <div class="mk-2 mb-3 text-decoration-underline">registered by
                    <strong style="text-decoration:underline">{{board.author.username}}</strong>
                </div>
                <div>{{board.create_date}}</div>
            </div>
            {%endif%}
        </div>
        <div class="my-3 p-3">
            {%if request.user == board.author%}
            <a class="btn btn-sm btn-outline-secondary" href="{%url 'board:board_modify' board.id%}">수정</a>
            <a class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'board:board_delete' board.id  %}"
               href="javascript:void(0)">삭제</a>
            {%endif%}
        </div>
    </div>
    <button class="btn btn-sm" style="margin-top:10px;background-color:#506EA5;color:white;" type="button"
        onclick="location.href='../'">목록이동
    </button>
    <a href="{%url 'board:board_create'%}" class="btn btn-primary btn-sm" style="margin-top:10px;float:right">게시글 등록</a>
    <!--질문 end-->
    <!--답변 등록 end-->
</div>
<!--container end-->
{%endblock%}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
<!--const delete_elements = document.querySelectorAll(".delete");-->
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/board/board_form.html
{%extends 'base.html'%}
{%block content%}
<!--container-->
<div class="container">
    <!--제목-->
    <div class="text-start mb-5">
        <h2 class="p-5">게시판등록</h2>
    </div>
    <!--제목 end-->

    <!--등록 form-->
<!--    <form method="post" class="post-form my-3" action="{%url 'board:board_create'%}">-->
    <form method="post" class="post-form my-3">
        {%csrf_token%}
        <!--form validation 기능-->
        {%include 'form_errors.html'%}
        <!--form validation 기능 end-->
        <div class="mb-3">
            <!--템플릿 필터 : 변수 값을 특정한 포맷으로 변형하는 기능.-->
            <label for="subject" class="col-form-label">제목</label>
            <div class="">
                <input type="text" class="form-control" id="subject" name="subject"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
        </div>
        <div class="mb-3">
            <label for="content" class="col-form-label">내용</label>
            <div class="">
                <!--content 에 데이터가 없으면 None 이라는 문자열이 표시됨, None 대신 공백으로 표시하세요.-->
                <textarea name="content" id="content" cols="20" rows="10" class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
        </div>
        <!--모델 폼과 연결된 subject, content 의 값을 저장할 수 있는 form 생성-->
        <button type="submit" class="btn btn-primary btn-sm">등록</button>
    </form>
    <!--등록 form end-->
</div>
<!--container end-->
{%endblock%}

templates/board/board_list.html
{% extends 'base.html' %}
{%load pybo_filter%}<!--사용자 정의 필터 로드-->
{% block content %}
    <!--container1-->
    <div class="container">
        <!--제목-->
        <div class="text-start mb-5">
            <h2 class="p-5">게시판</h2>
        </div>
        <div class="row my-3">
            <!--board 등록-->
            <div class="col-6">
                <a href="{% url 'board:board_create' %}" class="btn btn-primary">등록</a>
            </div>
            <!--board 등록 end-->
            <!--검색 버튼-->
            <div class="col-6">
                <div class="input-group">
                    <label for="search_div"></label><select id="search_div" class="select2-selection__choice">
                    <option value="" {% if div == '' %} selected {% endif %}>전체</option>
                    <option value="10" {% if div == '10' %} selected {% endif %}>제목</option>
                    <option value="20" {% if div == '20' %} selected {% endif %}>내용</option>
                    <option value="30" {% if div == '30' %} selected {% endif %}>작성자</option>
                </select>
                    <label for="search_kw"></label><input type="text" id="search_kw" class="form-control"
                                                          value="{{ kw|default_if_none:'' }}"
                                                          placeholder="검색어">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">조회</button>
                    </div>
                </div>
            </div>
            <!--검색 버튼 end-->
        </div>
        <!--제목 end-->
    </div>
    <div class="container table-responsible mt-5">
        <p>
            <label for="select_per_page">(총 {{ board_list.paginator.count }}개의 게시글이 검색되었습니다.)</label>
            <select name="per_page" id="select_per_page" class="form-select-sm">
                <option value="10" {% if per_page == '10' %} selected {% endif %}>10개씩 보기</option>
                <option value="20" {% if per_page == '20' %} selected {% endif %}>20개씩 보기</option>
                <option value="30" {% if per_page == '30' %} selected {% endif %}>30개씩 보기</option>
                <option value="50" {% if per_page == '50' %} selected {% endif %}>50개씩 보기</option>
                <option value="100" {% if per_page == '100' %} selected {% endif %}>100개씩 보기</option>
            </select>
        </p>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr class="text-center table-dark">
                <th>No.</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일</th>
            </tr>
            </thead>
            <tbody>
            {% if board_list %}
                {% for board in board_list %}
                    <tr class="text-center">
                        <!--일련 번호 = 전체 글수 - 시작 인덱스 - 현재 인덱스 + 1-->
                        <td>
                            {{ board.id }} <!--실제 질문 id 번호-->
                        </td>
                        <td class="text-start"><a href="{% url 'board:board_detail' board.id %}">{{ board.subject }}</a>
                        </td>
                        <td>{{ board.author.username }}</td> <!--글쓴이 추가-->
                        <td>{{ board.create_date|date:"Y-m-d" }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">"게시글이 없습니다."</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        {% csrf_token %}
        <!--페이징 처리-->
        <ul class="pagination justify-content-center">
            <!--첫페이지-->
            <li class="page-item">
                <a class="page-link"
                   href="?kw={{ kw|default_if_none:'' }}&page=1&div={{ div|default_if_none:'' }}&per_page={{ per_page|default_if_none:'' }}"
                   aria-label="&gt;">&laquo;</a>
            </li>
            <!--첫페이지 end-->
            <!--이전 페이지-->
            {% if board_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="javascript:void(0)">&lt;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-disabled="true" aria-label="&lt;">&lt;
                    </a>
                </li>
            {% endif %}
            <!--이전 페이지 end-->
            <!--페이지 리스트-->
            {% for page_number in board_list.paginator.page_range %}
                <!--현재 선택 페이지 와 나머지-->
                <!--페이지 번호가 현재 페이지 기준으로 좌우 5개씩 보이도록 처리-->
                {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
                    {% if page_number == board_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="javascript:void(0)" data-page="{{ page_number }}"
                               style="font-weight:bold">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item" aria-current="page">
                            <a class="page-link" href="javascript:void(0)" data-page="{{ page_number }}"
                               style="font-weight:bold">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!--페이지 리스트 end-->
            <!--다음 페이지-->
            {% if board_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ board_list.next_page_number }}"
                       href="javascript:void(0)">&gt;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" href="#" aria-disabled="true" aria-label="&gt;">&gt;
                    </a>
                </li>
            {% endif %}
            <!--다음 페이지 end-->
            <!--마지막 페이지-->
            <li class="page-item">
                <a class="page-link"
                   href="?kw={{ kw|default_if_none:'' }}&page={{ board_list.paginator.page_range.stop|sub:1 }}&div={{ div|default_if_none:'' }}&per_page={{ per_page|default_if_none:'' }}"
                   aria-label="&gt;">&raquo;</a>
            </li>
            <!--마지막 페이지 end-->
        </ul>
        <!--페이징 처리 end-->
    </div>
    <form action="{% url 'board:index' %}" id="searchForm" method="get">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="div" name="div" value="{{ div|default_if_none:'' }}">
        <input type="hidden" id="per_page" name="per_page" value="{{ per_page|default_if_none:'' }}">
    </form>
    <!--container end-->
{% endblock %}
{% block script %}
    <script type="text/javascript">
        function doRetrieve(page) { // page 변수 입력을 통해
            document.getElementById('kw').value = document.getElementById('search_kw').value;
            document.getElementById('page').value = page;
            document.getElementById('div').value = document.getElementById('search_div').value;
            document.getElementById('per_page').value = document.getElementById('select_per_page').value;
            document.getElementById('searchForm').submit();
        }

        const page_elements = document.getElementsByClassName("page-link");
        Array.from(page_elements).forEach(function (element) {
            element.addEventListener('click', function () {
                doRetrieve(this.dataset.page)
            });
        });
        const btn_search = document.getElementById("btn_search");
        btn_search.addEventListener('click', function () {
            doRetrieve(1);
        });
        const search_kw = document.querySelector("#search_kw");
        search_kw.addEventListener("keyup", function (event) {
            if (event.keyCode === 13) {
                doRetrieve(1);
            }
        });
        const per_page = document.getElementById("per_page");
        per_page.addEventListener("click", function () {
            doRetrieve(1);
        })
    </script>
{% endblock %}